version: "3.7"
services:
  todo:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    expose:
      - 8080
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=pg-user
      - POSTGRES_PASSWORD=pg-password
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    expose:
      - 5432